"""changed Painting database

Revision ID: 050ecb9aa56d
Revises: 8f7cc91c85e5
Create Date: 2023-11-17 10:49:47.751580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '050ecb9aa56d'
down_revision = '8f7cc91c85e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('created__imgs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('User', sa.String(length=255), nullable=False))

    with op.batch_alter_table('paintings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finetuning_description', sa.String(length=400), nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=400),
               existing_nullable=False)
        batch_op.alter_column('finetuning_path',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=400),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paintings', schema=None) as batch_op:
        batch_op.alter_column('finetuning_path',
               existing_type=sa.String(length=400),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(length=400),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('finetuning_description')

    with op.batch_alter_table('created__imgs', schema=None) as batch_op:
        batch_op.drop_column('User')

    # ### end Alembic commands ###
