"""added created paintings backref

Revision ID: 3f7d3c8f60b9
Revises: 050ecb9aa56d
Create Date: 2023-11-17 15:12:24.159115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f7d3c8f60b9'
down_revision = '050ecb9aa56d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('created__imgs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('created__imgs',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('original', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('votes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('User', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('path', name='created__imgs_pkey')
    )
    # ### end Alembic commands ###
