"""change collection field

Revision ID: 56a067de2c1e
Revises: 
Create Date: 2023-10-15 12:20:50.007516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56a067de2c1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('created_imgs')
    with op.batch_alter_table('museums', schema=None) as batch_op:
        batch_op.alter_column('Collection',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('museums', schema=None) as batch_op:
        batch_op.alter_column('Collection',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    op.create_table('created_imgs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('path', sa.VARCHAR(length=255), nullable=False),
    sa.Column('votes', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
