"""change museum unique

Revision ID: 61d987a31e0c
Revises: 56a067de2c1e
Create Date: 2023-10-15 16:10:21.742650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61d987a31e0c'
down_revision = '56a067de2c1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('museums', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['museum'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('museums', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
