"""added description field to Paintings

Revision ID: 8f7cc91c85e5
Revises: be5ac61977ec
Create Date: 2023-10-23 11:30:51.845885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f7cc91c85e5'
down_revision = 'be5ac61977ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paintings', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
