"""initial migration

Revision ID: be5ac61977ec
Revises: 56a067de2c1e
Create Date: 2023-10-20 16:09:29.468929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be5ac61977ec'
down_revision = '56a067de2c1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    pass
    # ### end Alembic commands ###
