"""initial migration

Revision ID: be5ac61977ec
Revises: 56a067de2c1e
Create Date: 2023-10-20 16:09:29.468929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be5ac61977ec'
down_revision = '56a067de2c1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('painting_temp')
    op.drop_table('finetuning')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finetuning',
    sa.Column('path', sa.VARCHAR(length=255), nullable=False),
    sa.Column('author', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('path'),
    sa.UniqueConstraint('author')
    )
    op.create_table('painting_temp',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('path', sa.VARCHAR(length=200), nullable=False),
    sa.Column('aut', sa.VARCHAR(length=100), nullable=False),
    sa.Column('painting', sa.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('path')
    )
    # ### end Alembic commands ###
