"""added blurImgs to paints

Revision ID: eb18b4171718
Revises: dd903a9e0eb3
Create Date: 2023-11-29 16:13:51.262748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb18b4171718'
down_revision = 'dd903a9e0eb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('created__imgs')
    with op.batch_alter_table('paintings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blur_imgs', sa.String(length=400), nullable=True))
        batch_op.drop_column('blurred_img_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paintings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blurred_img_path', sa.VARCHAR(length=400), autoincrement=False, nullable=True))
        batch_op.drop_column('blur_imgs')

    op.create_table('created__imgs',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('original', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('votes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('path', name='created__imgs_pkey')
    )
    # ### end Alembic commands ###
